## Introduction to Tensors

In [4]:
import tensorflow as tf
print(tf.__version__)

In [5]:
#Hello World of Tensors
#Create tensors w/ tf.constant()
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [6]:
#Check number of dimensions of tensor (ndim = no of dimensions)
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [8]:
vector.ndim
#from shape, number of dimensions come. 
# Example, shape of scalar had no element. And shape of vector has one.

1

In [10]:
# Create a matrix (more than one dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [11]:
another_matrix = tf.constant([[10, 57],
                     [7, 10],
                     [17, 13]], dtype=tf.float16) #Specifying the datatype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 57.],
       [ 7., 10.],
       [17., 13.]], dtype=float16)>

#### Specifying the datatype helps to less the space needed to store.
#### Such as int32 will take 32 space whereas 16 will take 16 spaces.
#### And if you get data type error, you can manipulate using the dtype.

In [12]:
another_matrix.ndim

2

In [13]:
# Create a tensor
tensor = tf.constant([[[10, 17, 30],
                     [10, 37, 350],],
                     [[50, 47, 340],
                     [70, 87, 320],],
                     [[90, 57, 315],
                     [134, 77, 360],]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 10,  17,  30],
        [ 10,  37, 350]],

       [[ 50,  47, 340],
        [ 70,  87, 320]],

       [[ 90,  57, 315],
        [134,  77, 360]]])>

In [14]:
tensor.ndim

3

### So Far:

* Scalar: A single number
* Vector: A Number w/ direction
* Matrix: A 2-dimensional array of numbers
* Tesnor: Can be a n-dimensional of array.