## Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
#Hello World of Tensors
#Create tensors w/ tf.constant()
scalar = tf.constant(8)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [3]:
#Check number of dimensions of tensor (ndim = no of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim
#from shape, number of dimensions come. 
# Example, shape of scalar had no element. And shape of vector has one.

1

In [6]:
# Create a matrix (more than one dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
another_matrix = tf.constant([[10, 57],
                     [7, 10],
                     [17, 13]], dtype=tf.float16) #Specifying the datatype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 57.],
       [ 7., 10.],
       [17., 13.]], dtype=float16)>

#### Specifying the datatype helps to less the space needed to store.
#### Such as int32 will take 32 space whereas 16 will take 16 spaces.
#### And if you get data type error, you can manipulate using the dtype.

In [8]:
another_matrix.ndim

2

In [9]:
# Create a tensor
tensor = tf.constant([[[10, 17, 30],
                     [10, 37, 350],],
                     [[50, 47, 340],
                     [70, 87, 320],],
                     [[90, 57, 315],
                     [134, 77, 360],]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 10,  17,  30],
        [ 10,  37, 350]],

       [[ 50,  47, 340],
        [ 70,  87, 320]],

       [[ 90,  57, 315],
        [134,  77, 360]]])>

In [10]:
tensor.ndim

3

### So Far:

* Scalar: A single number
* Vector: A Number w/ direction
* Matrix: A 2-dimensional array of numbers
* Tesnor: Can be a n-dimensional of array.

### Creating tensors w/ `tf.Variable`

In [11]:
changeable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7]) 
changeable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [12]:
#Changing value
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [13]:
#Trying to change value in unchangable
unchangable_tensor[0].assign(7)
unchangable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Rarely (in practice), you need to decide whether to use `constant` or `Variable` to create tensors. However, if needed, start with `tf.constant` and change if needed accordingly.

### Creating random tensors

Tensors of some random arbitrary size which contains totally random numbers.

In [14]:
random_1 = tf.random.Generator.from_seed(42) # setting seed for reproducibility; 42 is totally random
random_1 = random_1.normal(shape=(3,2))
random_1
#Normal Distribution = https://youtu.be/rzFX5NWojp0
random_2 = tf.random.Generator.from_seed(42) # setting seed for reproducibility
random_2 = random_2.normal(shape=(3,2))
random_2
#Uniform Distribution = https://www.youtube.com/watch?v=3C9mpj-NYgo

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

They generally produce pseudo-random numbers.
Fixing the seed helps to get the same value. Like Minecraft Seed Number.

#### Shuffling the orders of elements in a tensor 🔀 
https://www.tensorflow.org/api_docs/python/tf/random/set_seed?authuser=2

In [15]:
not_shuffled = tf.constant([[10, 57],
                     [7, 10],
                     [17, 13]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [17, 13],
       [10, 57]])>

In [16]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 57],
       [ 7, 10],
       [17, 13]])>

In [17]:
#Re-shuffling
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10, 57],
       [17, 13]])>

In [18]:
tf.random.set_seed(42) #global level random seed #fixing randomizing; random shuffle won't be there after that.
tf.random.shuffle(not_shuffled)
# tf.random.shuffle(not_shuffled, seed = 42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [17, 13],
       [10, 57]])>

It seems if we want our shuffled tensors in the same order, we need to use global level random seed as well as the operation level random seed.


### Other ways to make tensors

In [19]:
#Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
#Create a tensor of all zeros
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

#### Turn Numpy Arrays to Tensors
Main difference of np array and tf array(tensors) is that tensors can be run on a GPU.

In [28]:
import numpy as np
numpy_a = np.arange(1, 25, dtype=np.int32) #Creating a NumPy array between 1 and 25
# numpy_a

A = tf.constant(numpy_a, shape=(2, 3, 4)) 
B = tf.constant(numpy_a)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

##### To check how you can shape this into many dimension, you need to make sure the total number of shape is equal to the newly shaped array. Such as first array was of (24,) and talking about second one, it was (2, 3, 4) which technically is
#### 2X3X4 = 24 which is equal to the first one. 

In [29]:
C = tf.constant(numpy_a, shape=(8, 3)) 
C

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])>

#### 8X3 = 24 which is equal to the first one. 

## Getting info from Tensors

* Shape `tensor.shape`
* Rank `tensor.ndim` (Here, Scalar = Rank 0, Vector = Rank 1, Matrix = Rank 2, Tensor = Rank n)
* Axis/Dimension `tensor[0]`,`tensor[:, 1]`...
* Size `tf.size(tensor)`

In [30]:
# Creating a rank 5 tensor (5 dimensions)
tensor_5 = tf.zeros(shape=(2,3,4,5,6))
tensor_5

<tf.Tensor: shape=(2, 3, 4, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 

In [31]:
tensor_5[0]

<tf.Tensor: shape=(3, 4, 5, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0.

In [32]:
tensor_5.shape, tensor_5.ndim, tf.size(tensor_5)

(TensorShape([2, 3, 4, 5, 6]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=720>)

In [34]:
Size = 2 * 3 * 4 * 5 * 6 
Size

720

In [36]:
#Getting various attributes of tensor
print("Datatype of element of the tensor:",tensor_5.dtype)
print("# of dimensions (Rank):",tensor_5.ndim)
print("Shape of the tensor:",tensor_5.shape)
print("Element from the 0 axis:",tensor_5.shape[0])
print("Element from the last axis:",tensor_5.shape[-1])
print("Total Number of element of the tensor:",tf.size(tensor_5))

Datatype of element of the tensor: <dtype: 'float32'>
# of dimensions (Rank): 5
Shape of the tensor: (2, 3, 4, 5, 6)
Element from the 0 axis: 2
Element from the last axis: 6
Total Number of element of the tensor: tf.Tensor(720, shape=(), dtype=int32)


### Indexing Tensors
#### Tensors can be indexed just like Python Lists

In [39]:
some_list = [1,2,3,4]
print(some_list[:2])
tensor_5[:2, :2, :2, :2, :2]

[1, 2]


<tf.Tensor: shape=(2, 2, 2, 2, 2), dtype=float32, numpy=
array([[[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]],



       [[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]]], dtype=float32)>

In [43]:
#Getting the first element from each dimension from each index except 
#for the final one
tensor_5[:1, :1, :1, :1,]

<tf.Tensor: shape=(1, 1, 1, 1, 6), dtype=float32, numpy=array([[[[[0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [44]:
tensor_5[:1, :1, :, :1,]

<tf.Tensor: shape=(1, 1, 4, 1, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [45]:
tensor_5[:1, :, :1, :1,]

<tf.Tensor: shape=(1, 3, 1, 1, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [46]:
tensor_5[:, :1, :1, :1,]

<tf.Tensor: shape=(2, 1, 1, 1, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.]]]],



       [[[[0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [47]:
tensor_5[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5, 6), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [50]:
# Create a rank 2 tensor
tensor_2 = tf.constant([[10,7],
                      [3,4]])
tensor_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [51]:
tensor_2.shape, tensor_2.ndim

(TensorShape([2, 2]), 2)

In [52]:
# Getting the last item of each of row 
tensor_2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [54]:
# Adding extra dimension to the tensor
tensor_3 = tensor_2[:,:, tf.newaxis]
tensor_3 = tensor_2[..., tf.newaxis] # Line 2 and 3 are the same code
tensor_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [55]:
# Alternative of tf.newaxis
tf.expand_dims(tensor_2, axis=-1) # - 1 = expanding the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [57]:
tf.expand_dims(tensor_2, axis=0) # 0 = expanding the 0-th axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [58]:
tf.expand_dims(tensor_2, axis=1) # 1 = expanding the middle axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]])>